### ISSUE TITLE
Breaking change with impression collection in SDK version 7.0.0

### ISSUE THREAD

**Issue by engstrom** [splitio/python-client#123]
Apologies if you're already aware of this, but I didn't see anything regarding this in the changelog. 

There is a breaking change in SDK version 7.0.0 that causes impression collection to cease without throwing any errors when used with a synchronizer running version 1.6.0 of the splitsoftware/split-synchronizer docker image.

We have a synchronizer running on docker image version 1.6.0. When we upgraded from SDK version 6.2.2 to version 7.0.0 we stopped seeing impressions in the web portal. Upgrading our synchronizer's docker image to version 2.1.0 solved the issue but we lost any impressions that weren't still in redis.

It's possible that version 7.0.0 of the SDK has the same problem with other versions of the docker image but I haven't used it with any other version myself.

**Comment by mmelograno** [comment]
Hi @engstrom,

Thanks for the feedback and apologies for the inconveniences. This was only explained in detail in our [Synchronizer docs](https://docs.split.io/docs/split-synchronizer), but I have added it to the changelog here as well.

Again, thanks for the feedback.
Matias

**Comment by engstrom** [comment]
Thanks for confirming, @mmelograno. 👍

**Comment by engstrom** [comment]
Sorry, one last question, @mmelograno. The documentation you linked to says:
> (this is as easy as changing a parameter to true on the JSON config or an environment variable to on if you're using the docker image

But it doesn't say what the name of the parameter/variable is. Do you know?

**Comment by mmelograno** [comment]
Hi @engstrom,

The parameter is `disableLegacyImpressions`, we will update the documentation soon.

Thanks,
Matias
