### ISSUE TITLE
v8.0.0 Documentation

### ISSUE THREAD

**Issue by engstrom** [splitio/python-client#139]
The CHANGES.txt file mentions that the newest major version release (v8.0.0) includes a "Full SDK Refactor/rewrite" but doesn't describe the impacts of those changes to SDK users. Do you have any documentation hat outlines what steps we need to take in order to make our integration compatible with this new version?

**Comment by mredolatti** [comment]
Hello @engstrom, My apologies for the lack of information on the CHANGES file. 
Here's a link to our updated documentation: https://help.split.io/hc/en-us/articles/360020359652-Python-SDK .

The only thing you should worry about is, if you're using the `blockUntilReady` functionality. It has been removed from the configuration options, and placed into a method within the client factory.
Please refer to the following section for a snippet: https://help.split.io/hc/en-us/articles/360020359652-Python-SDK#2-instantiate-the-sdk-and-create-a-new-split-client

If you're using Redis or uWSGI as a synchronization platform, you needn't change anything.

You'll also notice information regarding the new `getTreatmentWithConfig` and `getTreatmentsWithConfig`. This functionality is still in closed beta but will be released very soon.

Please let me know if you find something missing or not clear enough on the documentation. And once again our apologies for the late release of the documentation corresponding to this version of the SDK.

Martin.

**Comment by engstrom** [comment]
Thanks, Martin. I'll look through the resources you've linked to.

**Comment by mredolatti** [comment]
I'm closing this for now. Please let me know if you have any further concerns.
Thank you for reaching out @engstrom
