### ISSUE TITLE
`xrange` not available in Python3

### ISSUE THREAD

**Issue by luisincrespo** [splitio/python-client#144]
https://github.com/splitio/python-client/blob/9a2f1780da9faa23085ddd5c3c9b4d0c074d1f6a/splitio/tasks/uwsgi_wrappers.py#L160

As you can see in the line above, you're using `xrange`, which is no longer available in Python3.

**Comment by chillaq** [comment]
Hi Luis, thanks for the info, will check internally to see how to fix it and keep compatibility with python 2.x

**Comment by mredolatti** [comment]
@luisincrespo `splitio_client==8.1.1` is out and includes your commit. Thank you very much.
I'll be closing this but don't hesitate to reach out again if you need further assistance or something's not working properly.

Thank you very much again and our apologies for any inconveniences caused.
