### ISSUE TITLE
Significant performance issue when upgrading to version 8

### ISSUE THREAD

**Issue by kstark** [splitio/python-client#160]
We recently attempted an upgrade to version 8.1.5 (using Python 2.7). We have a relatively simple integration, no external synchronizer and the only method we ever call is `client.get_treatment()` (with the client initialized once at app bootup, not per-request).  Despite that, we're seeing some serious latency when using the 8.1.5 version of the client.

As far as we can tell, it's triggered when we call `client.get_treatment()` while rendering a [Mako template](http://docs.makotemplates.org/en/latest/). Although we haven't completely finished our investigation, it looks like a large amount of time is spent inspecting the stack in [`_get_first_split_sdk_call`](https://github.com/splitio/python-client/blob/0bbd4180ddd89041fe527268c6691598ee1e2436/splitio/client/input_validator.py#L24-L38), which is called several times. My guess would be that the inspection is taking longer due to the Mako templates being compiled on-the-fly.

For reference, we're seeing ~20ms request times jump up into the 150-200ms range, with the only change being an upgrade of the split client version.

**Comment by mredolatti** [comment]
Hi @kstark! Thanks for reaching out with that issue, I can see how that stack inspection might cause performance issues. We'll release a fix for this either today before EOD or early tomorrow. We'll keep you posted.

**Comment by mredolatti** [comment]
Hi @kstark we've just released version 8.1.6 of our splitio_client package which removes stack inspection altogether. This should remediate the performance issue you were having. 
We apologize for any inconveniences caused, please don't hesitate to let us know and/or reopen this issue if the problem still occurs or you find anything else that's causing you trouble.

Thank you once again,
Martin.

**Comment by kstark** [comment]
Thanks @mredolatti for the quick turnaround, we'll give it a shot and let you know if we run into any issues.
