### ISSUE TITLE
`.block_until_ready` returns before SDK is ready

### ISSUE THREAD

**Issue by silasbw** [splitio/python-client#211]
**Behavior**: `.block_until_ready` returns and `.ready` evaluates to `False`, using the SDK results in warnings messages about not being ready, and `.splits` does not return expected results.

**Expected**: `.block_until_ready` returns and `.ready` evaluates to `True`, there are no warnings from the SDK about not being ready, and `.splits` returns the results we'd expect if the SDK was ready.

We're using version 8.2.1.

Repro:

```python
readiness_timeout_seconds = 5  # doesn't matter

factory.block_until_ready(readiness_timeout_seconds)
print(factory.ready)
```

We also see log warnings associated with calling the SDK when it's not ready (*e.g.*, https://github.com/splitio/python-client/blob/ae2de24cae86824a7cd386396cc7a6b35f3dc52b/splitio/client/manager.py#L54) and in some cases `.splits` does not return expected results.

**Comment by NicoZelaya** [comment]
Hi @silasbw ! 

Sorry to hear about the inconveniences, could you give it a try with the brand new 8.3.0 version of the SDK? We released a fix for block_until_ready functionality as part of that version. If you still experience the issue after the upgrade, we'll take a deeper look and issue the proper fix.

Thanks in advance,
Nico.

**Comment by chillaq** [comment]
Hi Silas, I am closing out this ticket. If there is still an open issue or if we can be of further assistance on this topic, feel free to respond to this email and the ticket will be re-opened.

Thanks
Bilal
