### ISSUE TITLE
mmh3cffi installation fails on linux with gcc

### ISSUE THREAD

**Issue by feljen** [splitio/python-client#219]
When attempting to install splitio with cpphash dependency on linux (CentOS 7) with gcc compiler, I get the following error in mmh3cffi 0.2.0:
```
csrc/mmh3.c:86:5: error: 'for' loop initial declarations are only allowed in C99 mode
```
The error does not occur on the previous version (0.1.5). Note I can successfully install with pip on MacOS.

**Comment by mredolatti** [comment]
Hi @feljen, thanks for pointing out this. We'll take a look and let you know. Would you mind sharing your GCC version?

**Comment by feljen** [comment]
Sure, it's gcc version 4.8.5. Thanks for looking into this!

**Comment by chillaq** [comment]
Hi @feljen , I found similar error when compiling numpy: https://github.com/numpy/numpy/issues/14182

The suggestion is to run this command before installing python library:
export CFLAGS='-std=c99'

Let me know if that fixes the issue.

**Comment by feljen** [comment]
Thanks for the reply @chillaq. We install this library across 20+ microservices so preferably this would be handled in the library itself rather than our builds. Does adding `extra_compile_args=['-std=c99']` to the library solve the issue?

**Comment by chillaq** [comment]
Hi @feljen , I would test the workaround before pushing it to all microservices, this is an issue with gcc 4.8.5 version.

**Comment by feljen** [comment]
Thanks but a workaround isn't sufficient, we need a fix for this issue. Can you reproduce the issue on your side?

**Comment by mredolatti** [comment]
Hi @feljen, sorry for the delay on this issue. We've updated mmh3cffi and its referenced in the new version `8.4.1`. This automatically requests that the build is done with C99 compatibility enabled. Please let me know if it works properly or you're still having issues.

Thank you very much, and once again sorry for the long delay on this!
Martin.

**Comment by feljen** [comment]
Yes, this works now! Thank you @mredolatti!
