### ISSUE TITLE
`SplitSynchronizer.synchronize_splits` can get stuck in an infinite loop

### ISSUE THREAD

**Issue by cfogg** [splitio/python-client#221]
We're seeing repeated calls to `api.fetch_splits` (hitting the sdk `splitChanges` endpoint) for the same change number. This seems to happen when a change event was generated that didn't update the `till` value of the response from the `splitChanges` REST call. Let's say the last change we fetched was t1, and there's an event at t2. In `synchronize_splits` we would first start with `split_storage.get_change_number()` and get t1 back, then re-fetch that. In normal operation, this would result in new data and an updated `till` value in the response. However, we see cases in production where the till value does not advance. Since the fetched `till` value is still less than t2, [this condition](https://github.com/splitio/python-client/blob/8.4.0/splitio/sync/split.py#L65-L66) is never met, and we don't break out of the `while True` loop that starts on line 43, and instead request t1 over and over.

I have a test that demonstrates the bug and a proposed fix in this [PR](https://github.com/cfogg/python-client/pull/1/files) on a fork. If you are interested in that PR, I can re-open it against this repo.

**Comment by patricioe** [comment]
Mind commenting in what geographic region you saw this behavior?

Thanks for bringing this to our attention

**Comment by cfogg** [comment]
Hi @patricioe, we saw this behavior in both our US East (Virginia) and US West (Phoenix) data centers.

**Comment by mredolatti** [comment]
Hi @cfogg , we are currently looking at this issue. It would be of great help if you could provide us with further details of your organization, so we better narrow our log searches to try and determine what went wrong.

 If you could reach our to support@split.io with the  following information?
- Organization name
- Name of the test/split that didn't get updated
- Environment name (the one your apikey being used in the troubled app belongs to)

Thanks!
Martin.

**Comment by mredolatti** [comment]
Hello @cfogg do you recall for how long it got stuck in the loop? We're trying to figure out a possible issue with our CDN expiration and  we'd like to know if the SplitFetcher took a couple of minutes and then synced (after some iterations) or if it stayed in a loop for say, a couple of hours, and never advanced.

Thank you very much for you help,
Martin.

**Comment by cfogg** [comment]
Hi @mredolatti, I saw a range of behaviors, some a few minutes, some a few hours, and various in between. My best guess was this had to do with what kind of changes were being made to splits via the dashboard, but this was hard to control for since we have lots of users making changes to splits. My sense was that certain changes were just skipped (the client would detect a change, try to fetch it, but it would have no data), it would get stuck in the loop, then it would clear up whenever the next change was made.

**Comment by mredolatti** [comment]
That's very useful. Thenk you very much @cfogg . We are actively working on finding the root cause of this. We will keep you informed on any progress.

Thanks once again and sorry for all the inconveniencies caused

**Comment by chillaq** [comment]
Hi @cfogg, Wanted to provide an update, we are actively investigating this issue with our CDN, we have enabled extended debugging logs and gathering the info to find a solution.

Will let you know once I have an update.

Thanks
Bilal

**Comment by mmelograno** [comment]
Hi @cfogg, we have just released `9.1.0` that includes a more polished retry-logic that should prevent this scenario. Nevertheless the loop is not infinite anymore but has a limited amount of retries per strategy.

Cheers
