### ISSUE TITLE
False instantiation > 1 warning when creating factories

### ISSUE THREAD

**Issue by brutledge-eb** [splitio/python-client#233]
When using the split synchronizer we don't pass an API key to `get_factory()`, and instead use `redisPrefix` in the config.

https://github.com/splitio/python-client/blob/31d207cf3bdc937b553f9ad852f0b894a9468684/splitio/client/factory.py#L468
This means this warning is set off every time we instantiate a new workspace with a new redisPrefix

**Comment by chillaq** [comment]
Hi @brutledge-eb , you still need to pass API Key when using Synchronizer, either the same API Key synchronizer uses or a custom API Key that is defined in synchronizer for security purposes.

The redisPrefix is only additional label for the redis keys that Synchronizer is using.

Thanks
Bilal

**Comment by brutledge-eb** [comment]
Hmm I'm able to create a workspace and retrieve values by passing a blank string there

**Comment by chillaq** [comment]
Using the Python SDK 9.0.0, if I runt he code below:

from splitio import get_factory
factory = get_factory('', config={'redisPrefix':'blah'}) 
split = factory.client()

I get the error below:
factory_instantiation: you passed an empty apikey, apikey must be a non-empty string.
Traceback (most recent call last):
  File "Main2.py", line 8, in <module>
    split = factory.client()
AttributeError: 'NoneType' object has no attribute 'client'

Which SDK version are you using?

**Comment by chillaq** [comment]
Hi @brutledge-eb ,  I am closing out this issue. feel free to respond if you need any further help.
