### ISSUE TITLE
Get full split information using the API?

### ISSUE THREAD

**Issue by mabr3** [splitio/python-client#257]
Hi, Is there any way to get the full information on a split using the API? I.e., receive which accounts are receiving each treatment in a certain Split?

**Comment by chillaq** [comment]
Hi @mabr3, We don't have an API endpoint that fetches the Impressions stored on Split side.

You can use the SDK listener to get the Impression record every time SDK generate it when getTreatment() function is called, you can then store the impression record any where on the cloud, checkout the docs: https://help.split.io/hc/en-us/articles/360020359652-Python-SDK#listener

Thanks

**Comment by mabr3** [comment]
Hi @chillaq, thanks for the reply, but that's not what I'm looking for. I want to know a priori which accounts were added to a certain split's different treatments. 

 One can actually get what I just described going through a somewhat cumbersome process:

```
import splitio
api_key = 'xxx'
http_client = splitio.api.client.HttpClient()
cfg = splitio.client.config.sanitize(api_key,  {})
sdk_metadata = splitio.client.util.get_metadata(cfg)
splits_api = splitio.api.splits.SplitsAPI(http_client, api_key, sdk_metadata)
splits_dict = splits_api.fetch_splits(0, None)

for i in range(0, len(splits_dict['splits'])):
  if splits_dict['splits'][i]['name'] == 'TARGET_SPLIT_NAME':
    break

splits_dict['splits'][i] 
```

Obviously this is just illustrative but the last line will then print the information on this split with the name TARGET_SPLIT_NAME, including which accounts get which treatment which was what I was looking for.

**Comment by mabr3** [comment]
Exactly. I was just wondering if there was an actual API for that or not and eventually I found how to get that data myself. Thanks for the reply though, let's close this. (also I wanted to label it as a question, but I'm unable to do so)
