### ISSUE TITLE
The `operationMode` is being modifying the settings of my application

### ISSUE THREAD

**Issue by eb-jorgemaroto** [splitio/python-client#258]
Hi,

reading [the documentation about setting up the SDK for redis](https://help.split.io/hc/en-us/articles/360020359652-Python-SDK#3-instantiate-the-sdk-client-with-redis-enabled), there isn't included the parameter `operationMode`, and it's being assigned by default if it's not set up:
https://github.com/splitio/python-client/blob/c5c84e484617b9caa40e752d74a76652c4ffe471/splitio/client/config.py#L119-L120

The issue is that we're storing the factory in a dictionary with the serialized config as a key, and we've seen that the second time that we're trying to serialize the config, it has been updated (adding that attribute to the settings), so it's been creating a second factory.

The way that we've solved this is by adding that key to the config as follows:
```python
SPLIT_CONFIG: {
    "apiKey": "",
    "redisHost": ...,
    ...
    ...
    'operationMode': 'redis-consumer',
....
}
```

Which would avoid adding that change to the settings. Is this something that should be documented? Is it something that we can lay on?

**Comment by eb-jorgemaroto** [comment]
OK, so it's safe to use it to avoid that the split SDK changes the configuration? (probably it would be better that the SDK doesn't modify the config passed as an argument but the copy that it's done, as it's [doing with the `DEFAULT_CONFIG`](https://github.com/splitio/python-client/blob/c5c84e484617b9caa40e752d74a76652c4ffe471/splitio/client/config.py#L120)).

**Comment by chillaq** [comment]
Yeah, I think we kept it to have backward compatibility with previous version, I would not use 'mode' as it will eventually get deprecated.
