### ISSUE TITLE
DeprecationWarning: setDaemon() is deprecated 

### ISSUE THREAD

**Issue by johachi** [splitio/python-client#294]
I'm getting the following warning in two places as of Python 3.10:

```sh
../lib/python3.10/site-packages/splitio/tasks/util/asynctask.py:132
  /lib/python3.10/site-packages/splitio/tasks/util/asynctask.py:132: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
    self._thread.setDaemon(True)

../lib/python3.10/site-packages/splitio/client/factory.py:139
  /lib/python3.10/site-packages/splitio/client/factory.py:139: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
    ready_updater.setDaemon(True)
```

Setting the daemon attribute instead has been the recommendation from at least Python 3.0.1 (https://docs.python.org/3.0/library/threading.html#threading.Thread.daemon).

**Comment by hbqdev** [comment]
Hi @johachi 
We're reviewing this issue and will get back to you.
For better assistance you can also create a ticket to Split support by sending an email to support@split.io
Thank you and Regards,

**Comment by hbqdev** [comment]
Hi @johachi 
This issue has been fixed

Regards
