### ISSUE TITLE
Publish wheels for splitio-client and mmh3cffi

### ISSUE THREAD

**Issue by dreid** [splitio/python-client#336]
It would be really great if splitio-client and mmh3cffi published wheels as documented at https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#wheels

Wheels have many benefits but most notably it they are usually smaller and faster to install.  For example an install of mmh3cffi takes ~7s on my machine, but an install of an mmh3cffi wheel takes only 2s.

I see that splitio-client is already using Github Actions so it seems like integrating https://cibuildwheel.readthedocs.io/en/stable/ would be rather straightforward.

**Comment by hbqdev** [comment]
Hi @dreid 
Thank you for the feedback, we have let our team know.

Regards,
