### ISSUE TITLE
SDK consistency

### ISSUE THREAD

**Issue by datv** [splitio/python-client#39]
The configuration fields should be consistent between the various SDKs.

Python on Flask uses { "redisHost", "redisPort" }
PHP uses { "cache": { "adapter" .... } }
Python SDK doesn't mention anything.

Python uses "ready"
Ruby uses "block_until_ready"
Node.js uses an event handler
Javascript uses "readyTimeout" + event handler

**Comment by patricioe** [comment]
Thank you @datv . We are aware of that and it's part of our todo list.

It should be addressed in future releases. 

The new upcoming features have config parameters that are consistent across languages.

Thanks for the feedback.

**Comment by NicoZelaya** [comment]
Since this is many years old and we're already pushing towards consistency, I'll go ahead and close the issue.
