### ISSUE TITLE
Split on Celery tasks

### ISSUE THREAD

**Issue by edufschmidt** [splitio/python-client#443]
Hi, I am wondering if you had any guides for using Split within Celery tasks. I noticed that it happens sometimes that if I try to evaluate a feature flag within a task running on a worker using a prefork pool, said flag is out of sync (its value is the value set on Split when the worker was spawned). The same doesn't happen with workers using a gevent pool. I suppose we might need to do something along the lines of what is recommended for using Split with uwsgi, but thought I'd ask to see if you had any suggestions.

**Comment by agustinona** [comment]
Hi @edufschmidt, I apologize for not being able to get back to you earlier on this. We don't have any specific guidelines for working Celery tasks. Please let me know if this is still an issue for you so we may look into it with our team, or if you have found a workaround.

**Comment by chillaq** [comment]
Hi @johnjameswhitman, I am curious, does the code you suggested works on celery?

Thanks
Bilal

**Comment by johnjameswhitman** [comment]
Yep, that celery signal is the crux of the fix; however, wiring it all together seemed to effect import order throughout our repo because we had to rearrange some things. If you end up having to do the same, then you might run into issues with things like decorators and other import side effects.

**Comment by chillaq** [comment]
Great, thanks.
