### ISSUE TITLE
Can't add newest library version using poetry because of missing bloom-filter2 package

### ISSUE THREAD

**Issue by Phantomo** [splitio/python-client#524]
Can somebody 
<img width="466" alt="image" src="https://github.com/splitio/python-client/assets/14827318/f2fb4833-548d-463a-ada0-521ae0f537f0">

**Comment by hbqdev** [comment]
Hi @Phantomo 

This is expected, you need to  manually install bloom-filter2, it is required for NONE impressions mode
Regards,

**Comment by Phantomo** [comment]
For all that have the same issue, I found solution. Like @hbqdev mention previously we need to manually install bloom-filter2 but with specify version
`poetry add bloom-filter2@2.0.0`
and after that installing of splitio_client passes successfully.
Maybe because without version poetry try to install strange version of bloom-filter 2 `^2.0.0.post1` and it broke everything.
